name: Build and test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: Build/Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Check out source
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod
        cache: true

    - name: Build
      run: go build ./...

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test ./... --race --timeout 60s

    - name: Vulnerability scan
      run: go run golang.org/x/vuln/cmd/govulncheck@v1.1.4 ./...
