name: Build and test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: Build/Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Check out source
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Build
      run: go build ./...

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test ./... --race --timeout 60s

    - name: Vulnerability scan
      run: go run golang.org/x/vuln/cmd/govulncheck@v1.1.4 ./...
